version: '3'

services:
  bash:
    build: .
    image: dannyben/alpine-ruby

  irb:
    image: dannyben/alpine-ruby
    command: irb

  version:
    image: dannyben/alpine-ruby
    command: |
      bash -c "printf 'Alpine : ' && cat /etc/alpine-release && printf 'Ruby   : ' && ruby --version"
